### ISSUE TITLE
Make targets for coding-standard are long

### ISSUE THREAD

**Issue by jost125** [bonami/collections#12]

**Comment by jost125** [comment]
I have created this issue based on TODO comment from CONTRIBUTING section. Although I am not sure, what the name should be.

I would like to not name it `phpcs`, because in future I would like to have standard for all code style checks across multiple languages.

What do you think @vasekboch ?

**Comment by vasekboch** [comment]
I was thinking about `fmt` and `fmtCheck` . fmt as command is widely used in GoLang, C++ and Scala. The autofix command is shorter, because that is what you want anyway.

**Comment by jost125** [comment]
Okey, no problem with that. BTW should the target have camelCase name? (We should standardize this as well)

**Comment by jost125** [comment]
@vasekboch I have shorten the names in https://github.com/bonami/collections/pull/22/commits/85d276c7b0173c63c7a65d319b831f403ae20a8e

Are you okay with it?

**Comment by vasekboch** [comment]
Yes. I think that the dash syntax is better.
